export type YouTubeResult={id:string;title:string;channelTitle:string;thumbnail:string;kind:'music'|'video'|'playlist';duration?:string;playlistId?:string};
export type QueueSeed={id:string;videoId:string;title:string;channelTitle:string;thumbnail:string;duration?:string;kind:'music'|'video'};
const API_BASE='https://www.googleapis.com/youtube/v3';
const getKey=()=>process.env.EXPO_PUBLIC_YOUTUBE_API_KEY?.trim()??'';
function formatDuration(value?:string){if(!value)return undefined;const m=value.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);if(!m)return undefined;const h=Number(m[1]??0),min=Number(m[2]??0),s=Number(m[3]??0);return h?String(h)+':'+String(min).padStart(2,'0')+':'+String(s).padStart(2,'0'):String(min)+':'+String(s).padStart(2,'0');}
export function youtubeConfigured(){return Boolean(getKey());}
async function api(path:string,params:Record<string,string>){const res=await fetch(API_BASE+path+'?'+new URLSearchParams(params).toString());const data=await res.json();if(!res.ok)throw new Error(data?.error?.message??'YouTube request failed.');return data;}
export async function searchYouTube(query:string,kind:'music'|'video'|'all'='all'){const key=getKey();if(!key)throw new Error('YouTube search is not configured. Add EXPO_PUBLIC_YOUTUBE_API_KEY to .env.local.');const data=await api('/search',{part:'snippet',q:query,type:kind==='music'?'video':'video,playlist',maxResults:'20',key,...(kind==='music'?{videoCategoryId:'10'}:{})});const ids=(data.items??[]).map((x:any)=>x.id?.videoId).filter(Boolean);const videos=ids.length?(await api('/videos',{part:'contentDetails,snippet',id:ids.join(','),key})).items??[]:[];const vr=videos.map((x:any):YouTubeResult=>({id:x.id,title:x.snippet?.title??'Untitled',channelTitle:x.snippet?.channelTitle??'YouTube',thumbnail:x.snippet?.thumbnails?.high?.url??x.snippet?.thumbnails?.medium?.url??x.snippet?.thumbnails?.default?.url??'',kind:kind==='music'?'music':'video',duration:formatDuration(x.contentDetails?.duration)}));const pr=(data.items??[]).filter((x:any)=>x.id?.playlistId).map((x:any):YouTubeResult=>({id:x.id.playlistId,playlistId:x.id.playlistId,title:x.snippet?.title??'Playlist',channelTitle:x.snippet?.channelTitle??'YouTube',thumbnail:x.snippet?.thumbnails?.high?.url??x.snippet?.thumbnails?.medium?.url??x.snippet?.thumbnails?.default?.url??'',kind:'playlist'}));return [...vr,...pr];}
export async function getPlaylistItems(playlistId:string):Promise<QueueSeed[]>{const key=getKey();if(!key)throw new Error('YouTube search is not configured.');const data=await api('/playlistItems',{part:'snippet,contentDetails',playlistId,maxResults:'50',key});const ids=(data.items??[]).map((x:any)=>x.contentDetails?.videoId).filter(Boolean);if(!ids.length)return [];const videos=(await api('/videos',{part:'contentDetails,snippet',id:ids.join(','),key})).items??[];return videos.map((x:any)=>({id:x.id,videoId:x.id,title:x.snippet?.title??'Untitled',channelTitle:x.snippet?.channelTitle??'YouTube',thumbnail:x.snippet?.thumbnails?.high?.url??x.snippet?.thumbnails?.medium?.url??'',duration:formatDuration(x.contentDetails?.duration),kind:'video'}));}
