import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { searchYouTube, youtubeConfigured, type YouTubeResult } from '../src/lib/youtube';

export default function Search(){
  const params=useLocalSearchParams<{kind?:'music'|'video'|'all';roomCode?:string}>();
  const [query,setQuery]=useState('');const [kind,setKind]=useState<'music'|'video'|'all'>(params.kind??'all');const [results,setResults]=useState<YouTubeResult[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!youtubeConfigured())setError('Add EXPO_PUBLIC_YOUTUBE_API_KEY to .env.local and restart Expo.');},[]);
  async function search(){if(!query.trim())return;setLoading(true);setError('');try{setResults(await searchYouTube(query.trim(),kind));}catch(e){setError(e instanceof Error?e.message:'Search failed.');}finally{setLoading(false);}}
  return <SafeAreaView style={s.c} edges={['top','bottom']}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.kicker}>DISCOVER</Text><Text style={s.title}>Find your vibe</Text></View></View><View style={s.search}><Text style={s.mag}>⌕</Text><TextInput autoFocus value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Search songs, artists, videos, playlists..." placeholderTextColor="#6f6c78" style={s.input} returnKeyType="search"/><TouchableOpacity onPress={search} disabled={loading}><Text style={s.go}>{loading?'…':'Go'}</Text></TouchableOpacity></View><View style={s.tabs}>{(['all','music','video'] as const).map(x=><TouchableOpacity key={x} style={[s.tab,kind===x&&s.tabOn]} onPress={()=>{setKind(x);setResults([]);setError(youtubeConfigured()?'':'Add EXPO_PUBLIC_YOUTUBE_API_KEY to .env.local and restart Expo.')}}><Text style={[s.tabText,kind===x&&s.tabTextOn]}>{x==='all'?'Everything':x==='music'?'🎵 Music':'🎬 Videos'}</Text></TouchableOpacity>)}</View>{error?<View style={s.notice}><Text style={s.noticeTitle}>Search setup</Text><Text style={s.noticeText}>{error}</Text></View>:null}<ScrollView contentContainerStyle={s.list}>{loading?<ActivityIndicator size="large"/>:results.map(item=><ResultCard key={item.id+item.kind} item={item} roomCode={params.roomCode}/>) }{!loading&&!results.length&&!error?<Text style={s.empty}>Search for a song, artist, video or playlist.</Text>:null}</ScrollView></SafeAreaView>;
}
function ResultCard({item,roomCode}:{item:YouTubeResult;roomCode?:string}){
  const next=roomCode?{pathname:'/room',params:{code:roomCode,videoId:item.kind==='playlist'?'':item.id,playlistId:item.playlistId??'',title:item.title,channel:item.channelTitle,thumbnail:item.thumbnail,kind:item.kind}}:{pathname:'/create',params:{videoId:item.kind==='playlist'?'':item.id,playlistId:item.playlistId??'',title:item.title,channel:item.channelTitle,thumbnail:item.thumbnail,kind:item.kind}};
  return <TouchableOpacity style={s.card} onPress={()=>router.push(next as any)}><Image source={{uri:item.thumbnail}} style={s.thumb}/><View style={s.meta}><View style={s.badgeRow}><Text style={s.type}>{item.kind==='playlist'?'PLAYLIST':item.kind==='music'?'MUSIC':'VIDEO'}</Text>{item.duration?<Text style={s.duration}>{item.duration}</Text>:null}</View><Text numberOfLines={2} style={s.cardTitle}>{item.title}</Text><Text numberOfLines={1} style={s.channel}>{item.channelTitle}</Text></View><Text style={s.plus}>{item.kind==='playlist'?'›':'＋'}</Text></TouchableOpacity>;
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:'#08070d',padding:18},header:{flexDirection:'row',alignItems:'center',marginTop:12,marginBottom:18},back:{color:'#fff',fontSize:38,marginRight:10,lineHeight:38},kicker:{color:'#a78bfa',fontSize:10,fontWeight:'900',letterSpacing:2},title:{color:'#fff',fontSize:26,fontWeight:'900',marginTop:2},search:{height:56,backgroundColor:'#15131d',borderRadius:17,borderWidth:1,borderColor:'#2a2732',flexDirection:'row',alignItems:'center',paddingHorizontal:14},mag:{fontSize:25,color:'#a78bfa',marginRight:8},input:{flex:1,color:'#fff',fontSize:15},go:{color:'#c4b5fd',fontWeight:'900'},tabs:{flexDirection:'row',gap:8,marginVertical:14},tab:{paddingHorizontal:15,paddingVertical:9,borderRadius:999,backgroundColor:'#111019'},tabOn:{backgroundColor:'#2b1b55'},tabText:{color:'#777481',fontWeight:'700'},tabTextOn:{color:'#ddd0ff'},notice:{backgroundColor:'#171128',borderWidth:1,borderColor:'#4c2d83',padding:14,borderRadius:16},noticeTitle:{color:'#fff',fontWeight:'800'},noticeText:{color:'#aaa3b6',marginTop:5,lineHeight:19},list:{paddingBottom:30,gap:10},empty:{color:'#696673',textAlign:'center',marginTop:60},card:{flexDirection:'row',alignItems:'center',backgroundColor:'#111019',borderRadius:16,padding:8,borderWidth:1,borderColor:'#201d27'},thumb:{width:118,height:72,borderRadius:10,backgroundColor:'#201d27'},meta:{flex:1,paddingHorizontal:11},badgeRow:{flexDirection:'row',gap:8,alignItems:'center'},type:{color:'#a78bfa',fontSize:9,fontWeight:'900',letterSpacing:1},duration:{color:'#65616d',fontSize:10},cardTitle:{color:'#fff',fontSize:14,fontWeight:'800',lineHeight:19,marginTop:4},channel:{color:'#908c99',fontSize:12,marginTop:4},plus:{color:'#c4b5fd',fontSize:27,paddingHorizontal:8}});